version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: vote
    restart: always
    environment:
      MYSQL_DATABASE: vote
      MYSQL_USER: vote
      MYSQL_PASSWORD: vote
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data: